#!/bin/bash

function align_text_bottom_offset {

  offset_text="$1"

  text=`ralign "$2"`

  rows=`tput lines`

  text_length=`echo -e "$text" | wc -l | tr -d ' '`
  center=`expr \( $rows \) - $text_length - $offset_text - 1`

  lines=""

  for i in `seq $center`
  do
    lines="$lines\n"
  done

  echo -e "$lines$text"

}

function align_text_bottom {
  text=$1

  rows=`tput lines`

  text_length=`echo -e "$text" | wc -l | tr -d ' '`

  center=`expr \( $rows \) - $text_length`

  lines=""

  for i in `seq $center`
  do
    lines="$lines\n"
  done

  echo -e "$lines$text"
}

function ralign {

  text="$1"

  cols=`tput cols | tr -d ' '`

  IFS=$'\n'$'\r'
  for line in $(echo -e "$text"); do

    line_length=`echo -e "$line" | wc -c | tr -d ' '`
    right=`expr \( $cols \) - $line_length`

    spaces=""
    for i in `seq $right`
    do
      spaces="$spaces "
    done

    echo -e "$spaces$line"

  done

}

function hcenter {

  text="$1"

  cols=`tput cols`

  # http://blog.edwards-research.com/2010/01/quick-bash-trick-looping-through-output-lines/
  # http://gslsrc.net/l007_loops_in_bash.html

  IFS=$'\n'$'\r'
  for line in $(echo -e "$text"); do

    line_length=`echo "$line" | wc -c | tr -d ' '`
    half_of_line_length=`expr $line_length / 2`
    center=`expr \( $cols / 2 \) - $half_of_line_length`

    spaces=""
    for i in `seq $center`
    do
      spaces="$spaces "
    done

    echo "$spaces$line"

  done

}

function vcenter {

  text=$1

  rows=`tput lines`

  text_length=`echo -e "$text" | wc -l | tr -d ' '`
  half_of_text_length=`expr $text_length / 2`
  center=`expr \( $rows / 2 \) - $half_of_text_length`

  lines=""

  for i in `seq $center`
  do
    lines="$lines\n"
  done

  echo -e "$lines$text"
}

function center {
  text="$1"
  vcenter "`hcenter "$text"`"
}


